### ISSUE TITLE
Achievement Icons/Descriptions

### ISSUE THREAD

**Issue by kierajreed** [olleharstedt/civ-clicker#10]
I have made icons for all but 3 achievements, do you know how to implement them?
Also, some way of showing how you got the achievements is good.

**Comment by olleharstedt** [comment]
You made icons?? That's awesome!

Yes, there should be a notification/popup when you're granted an achievement.

**Comment by olleharstedt** [comment]
Feel free to join the ##incremental IRC channel on freenode for more discussion.

**Comment by olleharstedt** [comment]
Another good idea might be to post your pics on /r/civclicker subreddit. That way, all versions of the game can use them.

**Comment by kierajreed** [comment]
Unfortunately, I don't have reddit, so I will upload them here.
Also, Ghost Town, Engineer, and Full House are not done, and some others need improvement.
Should I upload directly to images or images/achievements?
Sneak peek:
![14 - domination](https://user-images.githubusercontent.com/29524963/29489308-c109e99c-84eb-11e7-96c5-463a3f10d19b.png)
![30 - rushed](https://user-images.githubusercontent.com/29524963/29489306-bccf428c-84eb-11e7-85e3-59d5bf81e936.png)
![31 - neverclick](https://user-images.githubusercontent.com/29524963/29489307-bcd59c86-84eb-11e7-82f6-8eaf4bc2e8b7.png)

**Comment by olleharstedt** [comment]
Cool! You can do a pull request and I will merge the icons and then update the code to use them.

**Comment by kierajreed** [comment]
Hey Olle, I think that new properties such as ```achIcon``` or ```achTitle``` can be useful.

**Comment by olleharstedt** [comment]
Yes, either that or name the files the same as the achievements.

**Comment by olleharstedt** [comment]
This is how it looks with all achievements unlocked:

![Achievements](https://i.snag.gy/3isUvf.jpg)

**Comment by olleharstedt** [comment]
Also, I hope you realize that the icons have to be open-source licensed?

**Comment by kierajreed** [comment]
What exactly does that mean for me?

**Comment by olleharstedt** [comment]
That anyone can use them _if_ they include your name.

**Comment by olleharstedt** [comment]
I think... Google creative commons license for more info.

**Comment by kierajreed** [comment]
Ok then, how do I go about doing it?
Creative Commons BY-NC seems like the one I would use.

**Comment by olleharstedt** [comment]
We should add a note about it in the FAQ, right after the note about game-icons.net.

**Comment by olleharstedt** [comment]
Like, "All images in folder achievements/ are made by < your name > and licensed under CC-BY."

**Comment by kierajreed** [comment]
Sure, and since this issue is done I am closing it as well.
