### ISSUE TITLE
General Discussion 

### ISSUE THREAD

**Issue by kierajreed** [olleharstedt/civ-clicker#20]
Talk about coding here
Do not close until 50 messages

**Comment by olleharstedt** [comment]
About wiki, shame, maybe I can setup something on the server instead.

**Comment by kierajreed** [comment]
And, I've tried `grep`, but Windows does not want to cooperate.

[SIDE NOTE] pull request #15

**Comment by kierajreed** [comment]
About the wiki: [MediaWiki Setup](https://www.mediawiki.org/wiki/Manual:Installing_MediaWiki) and [This Guide](http://lifehacker.com/163707/geek-to-live--set-up-your-personal-wikipedia)

**Comment by kierajreed** [comment]
Actually, the wiki works now.

**Comment by kierajreed** [comment]
I added population and a `siliconage` branch

**Comment by olleharstedt** [comment]
Cool!

Did you manage to get your game up and running on your machine? Consider installing WAMP: http://www.wampserver.com/en/

It includes MySQL and PHP too, which are not needed for CivClicker, but it's an easy. automatic setup.

**Comment by kierajreed** [comment]
No, but I would like to host the game locally.

**Comment by kierajreed** [comment]
How do I add a trigger to achievements and stuff to buildings?
Where is this stored?

**Comment by olleharstedt** [comment]
For achievements, checkout the function `updateAchievements()` in civclicker-update.js.

For stuff to buildings, can you be more specific? :) Did you check the Building class in scripts/classes/?

**Comment by olleharstedt** [comment]
Nice work on the wiki, btw!

**Comment by kierajreed** [comment]
Specifically,
1. `Apartment` which *would* add population.
2. Another building which would allow new jobs.
3. A new type of building (to process resources).

[SIDE NOTE]: Add deconstruction/building removal?

**Comment by kierajreed** [comment]
```
/**
 * Displays achievements if they are unlocked
 * Called on each tick.
 */
function updateAchievements() {
  achData.forEach(function(achObj) {
    let ach = $('#' + achObj.id);
    if (achObj.owned) {
      ach.show();
      ach.html(`<img src='images/achievements/${achObj.id}.png' />`);
    } else {
      ach.hide();
    }
  });
}
```
I don't see what unlocks the achievements...
Or what buildings do... ([code](https://github.com/olleharstedt/civ-clicker/blob/siliconage/scripts/classes/Building.js))
My version of `civclicker-data`: [civclicker-data](https://github.com/olleharstedt/civ-clicker/blob/siliconage/scripts/civclicker-data.js)

**Comment by SkyHawkB** [comment]
Or what building do... ([code](https://github.com/olleharstedt/civ-clicker/blob/siliconage/scripts/classes/Building.js))

**Comment by kierajreed** [comment]
very side note: the bug where sick workers don't count towards max population

**Comment by kierajreed** [comment]
extremely-not-even-civcliker side note:
[my attempt at porting a board game](https://jsfiddle.net/06kef9da/11/)
WARNING: VERY MESSY CODE

**Comment by kierajreed** [comment]
Hey olle, mind adding `siliconage` to your server?
Also, we have to make sure that `siliconage` and `stoneage` don't have conflicting variables.
PS how do I add the weather plugin to `siliconage`?

**Comment by kierajreed** [comment]
Random thought: when did Woodstock and Orteil become the default names?

**Comment by olleharstedt** [comment]
I could do that, but I think first you have to have it running on your computer. It will be impossible for you to develop otherwise. Just ask if you need any help.

For random names, don't know. :) Check `git blame` on those lines.

**Comment by olleharstedt** [comment]
To avoid conflicts, the two branches should merge continually, either silicon into stoneage or the other way around.

**Comment by kierajreed** [comment]
`silicon -> stone`
`Stone` has many more useful plugins, and I barely started to add buildings anyway.

**Comment by olleharstedt** [comment]
OK, but I'd prefer not to merge until you have tested all your code on your own machine.

**Comment by olleharstedt** [comment]
The commit is about probability distribution. It's from statistics and stuff. Basically, we want to find out that, if it rains, how much does it rain? There are academic papers about these issues, so I read them and try to imitate their results. Does that make it more clear?

**Comment by olleharstedt** [comment]
There's a wikipedia article about gamma distribution here: https://en.wikipedia.org/wiki/Gamma_distribution

**Comment by olleharstedt** [comment]
And here's a PDF about how the gamma distribution can be used in analyzing rain fall: http://journals.tubitak.gov.tr/engineering/issues/muh-00-24-6/muh-24-6-7-9909-13.pdf

**Comment by olleharstedt** [comment]
I did not write the implementation of the gamma distribution, the source link is in the commit.

**Comment by olleharstedt** [comment]
Here's a blog post about how to generate weather using statistical methods, in Python: http://semaj.co.uk/stochastic-simulation-of-daily-rainfall-with-python.html

**Comment by olleharstedt** [comment]
One last thing that will be added to rain fall is a coefficient from the season. Something like

    rainfall = gamma(rand) * season(dayOfYear)

where `season()` is a Fourier function.

**Comment by olleharstedt** [comment]
This article has pretty good pictures about Fourier series: http://mathworld.wolfram.com/FourierSeries.html

**Comment by olleharstedt** [comment]
I mean, this math is above my level, I'm just stealing it to make the weather simulation more realistic. :)

**Comment by olleharstedt** [comment]
You can google for "stochastic weather generator" for more info.

**Comment by kierajreed** [comment]
I don't get it but it makes the game better anyways. ;)

**Comment by kierajreed** [comment]
@olleharstedt I've decided to delete `siliconage` so that we can focus on `stoneage` more.
React with 👎 by 09/09/17 to prevents this action.

**Comment by kierajreed** [comment]
Especially because plugins.
Eg: `Solar Panel` - `+1 energy during the day`.

**Comment by olleharstedt** [comment]
You do as you like. :) No reason to delete any material, and no reason to take any big decisions. Just keep working with what's interesting for you. As a hobby project, learning should be the biggest motivation. Also feel free to conceptualize the silicon age in the wiki if you feel like it, not everything has to be coding.

**Comment by kierajreed** [comment]
Can I get a code tour and class?

I have never seen `subscribe` before, or GitHub download,
I want to know how `tick`, `night`, and `day` go,
I need to see the building code,
and what the workers do,
explain how wolves can live abroad,
and learn `Achievements` all anew.

XD poems

**Comment by olleharstedt** [comment]
Well, I can't teach you how to code. There are courses for that, and lots of other people who are ready to help you. I can help to explain specific pieces in the code, but I can't give you an overview, because I didn't read all the code yet!

**Comment by kierajreed** [comment]
Ya... I want a tour, so when you can, please give me pointers like how to add Buildings and stuff.
I can code but I don't understand this game's code.

**Comment by kierajreed** [comment]
I'm also not that good, so if you can give me some tips on where to learn more advanced things.

**Comment by olleharstedt** [comment]
First step must be to install WAMP (if you're on Windows).

If you want to improve your JavaScript skills and/or get general tips, you can post or read on

￼https://www.reddit.com/r/learnjavascript/

or visit the IRC channel `#javascript`.

Google for "windows irc client" to find IRC clients.

**Comment by kierajreed** [comment]
I made a Discord Bot!

**Comment by olleharstedt** [comment]
Cool. :)

**Comment by kierajreed** [comment]
Repo: https://github.com/SkyHawkB/basic-bot

**Comment by kierajreed** [comment]
So I've made some pretty cool code!

**Comment by olleharstedt** [comment]
Yeah, looks good! :)

**Comment by kierajreed** [comment]
So is weather not in-game yet?
BTW `Hearths` should increase temperature at night by consuming wood, maybe even a `fire-watchman` worker?

**Comment by olleharstedt** [comment]
No, it's not, I have to sync the seasons so rain and temp are following each other.

**Comment by kierajreed** [comment]
Oh. But rain and temp are independent IRL, just make the seasons rig both separately.

**Comment by olleharstedt** [comment]
They are in fact not independent, but both season dependent. :)

**Comment by kierajreed** [comment]
Good. what about `Hearth`s? Do they affect gameplay yet?

**Comment by kierajreed** [comment]
Moving to next issue after next comment.

**Comment by olleharstedt** [comment]
Nope. But as you said, they should protect citizens from low temperature.

**Comment by kierajreed** [comment]
Moved to issue #23.
