### ISSUE TITLE
General Discussion 2

### ISSUE THREAD

**Issue by kierajreed** [olleharstedt/civ-clicker#23]
stuff

**Comment by olleharstedt** [comment]
\o/

**Comment by kierajreed** [comment]
So how would `Hearth`s work?
Would the consume wood, and how?

**Comment by olleharstedt** [comment]
(At work, will continue discussion later.)

**Comment by kierajreed** [comment]
So...

**Comment by kierajreed** [comment]
`Hearth`s

**Comment by kierajreed** [comment]
Also, at what point would #7 and #18 be considered `closed`?

**Comment by kierajreed** [comment]
also, #5 can be closed right?

**Comment by olleharstedt** [comment]
I wouldn't close climate - it's like weather but even more long term, like changing due to CO2 pollution and other things.

**Comment by olleharstedt** [comment]
I'll close weather when I've finished version 1 of the weather plugin (should be much work).

**Comment by olleharstedt** [comment]
Skills and tools far from done, I'm afraid. :P

**Comment by olleharstedt** [comment]
I created two new issues, for hearth and wolfs/wild animals.

**Comment by kierajreed** [comment]
Cool.

**Comment by kierajreed** [comment]
Can #2, #3, and #4 be removed from the project?

**Comment by kierajreed** [comment]
Or moved to `Done`?

**Comment by kierajreed** [comment]
- Would `Hearth`s need a worker to keep the fire going?
- How would they consume wood and add (local?) temp?

**Comment by olleharstedt** [comment]
Did you close the new issues by mistake?

**Comment by kierajreed** [comment]
As they are in a project I thought they were intended to be cards representing the objects. Sorry.

**Comment by kierajreed** [comment]
@olleharstedt I reopened them.

**Comment by kierajreed** [comment]
Also, how far are #2, #3, and #4 on being done?

**Comment by kierajreed** [comment]
Or what is their state?

**Comment by olleharstedt** [comment]
Hm, no work done on those issues. Sorry, I've been a bit stressed out the last week, and now I have a cold, too. >< Next step for me is to put all the weather simulation tests into the game, with icons and proper interface.

**Comment by kierajreed** [comment]
so what do the new commits do?

**Comment by kierajreed** [comment]
and where is `getDryTemperature();`, why is there no `getWetTemperaure();`, and why does it return  a string

**Comment by olleharstedt** [comment]
Finally fixing loading/saving of culture conditions; `getDryTemperature()` returns a function that can be used to calculate temperature. Didn't have time to implement wet temperature, I think I will just integrate what I have - weather simulation 0.1 alpha :) - and go with it; can't dwell on it forever, hopefully there will be time to improve upon it later.

**Comment by kierajreed** [comment]
where is the function that calculates temperature written?

**Comment by kierajreed** [comment]
I would like to add some things as well as wet temperature

**Comment by kierajreed** [comment]
also for the health plugin - can you explain how I can access temperature, etc?

**Comment by olleharstedt** [comment]
The getTemperature function is copy-pasted from this academic paper:

https://www.researchgate.net/publication/228543743_Climak_A_stochastic_model_for_weather_data_generation

**Comment by olleharstedt** [comment]
You get the temperature by subscribing to the `weather.temperature` event.

**Comment by olleharstedt** [comment]
Did you install Apache2 on your computer yet?

**Comment by kierajreed** [comment]
No. I am thinking to install WAMP, which includes Apache.

What is subscribing and how does it work? (<- am noob coder)

**Comment by olleharstedt** [comment]
Yeah, WAMP is a good choice.

Subscription is a so called programming design pattern. Maybe this page explains it well? https://sourcemaking.com/design_patterns/observer

**Comment by kierajreed** [comment]
cool!

**Comment by olleharstedt** [comment]
Some free online books you might be interested in:

The ES6 version of JavaScript (I use this for CivClicker 2): https://leanpub.com/understandinges6/read

Design patterns for games: http://gameprogrammingpatterns.com/contents.html

**Comment by olleharstedt** [comment]
SICP is a classic, too. It uses the Scheme programming language, which is said to be one of the inspirations for JavaScript. This book was used as introduction course on MIT. https://mitpress.mit.edu/sicp/full-text/book/book.html

**Comment by kierajreed** [comment]
Thank you!

**Comment by kierajreed** [comment]
How do I get the number of Hearths?

I am adding them to the temperature.

**Comment by kierajreed** [comment]
Also, can you please look at #27 and tell me if I did it right?

**Comment by olleharstedt** [comment]
To get number of buildings, there's a global object called `curCiv`. Number of owned hearths is in `curCiv.hearths.owned`.

**Comment by olleharstedt** [comment]
Optimally, all these global variables should be put in the namespace object `CivClicker`.

**Comment by olleharstedt** [comment]
Another global variable to checkout is `civData`.

**Comment by kierajreed** [comment]
does `civData` hold the amount of resources by any chance?

**Comment by kierajreed** [comment]
because then
```
let hearthsOwned = curCiv.hearths.owned;
/*amount of wood */ -= hearthsOwned;
```

this would decrement the wood owned by 1 per hearth every tick
in the description you would add `Consumes 1 Wood/Sec.`

**Comment by kierajreed** [comment]
hmm. just took a good look at `civclicker-data` and saw a bunch of stuff 😄

**Comment by kierajreed** [comment]
@olleharstedt are #28 and #29 ready to merge?

**Comment by kierajreed** [comment]
Olle can you please add the newest version instead if 2.0.0?

**Comment by olleharstedt** [comment]
Hm, which newest version? It's still 2.0-alpha.

**Comment by kierajreed** [comment]
the one you just added #28 to

**Comment by kierajreed** [comment]
Moving to #30; this is getting long.
